src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $video_source;

    /**
     * @ORM\Column(type="text")
     */
    private $video_title;

    /**
     * @ORM\Column(type="text")
     */
    private $video_description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $video_preview;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $user_ip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_agent;

    /**
     * @ORM\Column(type="datetime")
     */
    private $time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVideoSource(): ?string
    {
        return $this->video_source;
    }

    public function setVideoSource(string $video_source): self
    {
        $this->video_source = $video_source;

        return $this;
    }

    public function getVideoTitle(): ?string
    {
        return $this->video_title;
    }

    public function setVideoTitle(string $video_title): self
    {
        $this->video_title = $video_title;

        return $this;
    }

    public function getVideoDescription(): ?string
    {
            return $this->video_description;
    }

    public function setVideoDescription(string $video_description): self
    {
        $this->video_description = $video_description;

        return $this;
    }

    public function getVideoPreview(): ?string
    {
            return $this->video_preview;
    }

    public function setVideoPreview(string $video_preview): self
    {
        $this->video_preview = $video_preview;

        return $this;
    }

    public function getUserIp(): ?string
    {
        return $this->user_ip;
    }

    public function setUserIp(string $user_ip): self
    {
        $this->user_ip = $user_ip;

        return $this;
    }

    public function getUserAgent(): ?string
    {
        return $this->user_agent;
    }

    public function setUserAgent(string $user_agent): self
    {
        $this->user_agent = $user_agent;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/VideoController.php
<?php



namespace App\Controller;

use App\Controller\Datatime;
use App\Entity\Video;
use App\Service\CoreService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

ini_set('max_execution_time', 1500);

class VideoController extends AbstractController
{
    public function index(Request $request)
    {
        $service = new CoreService();
        $data = $service->initParse();
        foreach ($data as $item) {
            $video = new Video();
            $em = $this->getDoctrine()->getManager();
            $video->setVideoTitle($item['video_title'])
                  ->setTime(new \Datetime('now'))
                  ->setStatus($this->getDoctrine()->getRepository(Video::class)->findAllBySource("https://www.youtube.com/watch?v=".$item['video_source']))
                  ->setVideoDescription($item['video_description'])
                  ->setVideoPreview("https://lexani.com/img/".$item['video_preview'])
                  ->setVideoSource("https://www.youtube.com/watch?v=".$item['video_source'])
                  ->setUserIp($request->getClientIp())
                  ->setUserAgent($request->headers->get("User-Agent"));
            $em->persist($video);
            $compare = $this->getDoctrine()->getRepository(Video::class)->findBy(['video_source'=> $video->getVideoSource()]);
            $em->flush();
            $em->clear();
        }
        $videos = $this->getDoctrine()->getRepository(Video::class)->findAll();
        $export = $service->initCSV($videos);
        return $this->render('video/index.html.twig', ['videos' => $videos]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lexani Grabber{% endblock %}

{% block body %}
    <header class="container">
        <h1>Lexani Grabber</h1>
    </header>
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Status</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Preview</th>
                <th scope="col">Video</th>
            </tr>
            </thead>
            <tbody>
            {% for video in videos %}
            <tr>
                <th scope="row">{{ video.id }}</th>
                <td>{{ video.status }}</td>
                <td>{{ video.videoTitle }}</td>
                <td>{{ video.videoDescription }}</td>
                <td><a href="{{ video.videoPreview }}">Preview</a></td>
                <td><a href="{{ video.videoSource }}">Video</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}